default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: 'nixpkgs-fmt'
        name: 'nixpkgs-fmt'
        description: 'Format nix code with nixpkgs-fmt'
        entry: 'nixpkgs-fmt'
        language: 'system'
        files: '\.nix$'
        always_run: true
